swagger: "2.0"
info:
  description: "This is a sample swagger static page hosted on github. For full sample swagger yaml can refer to https://editor.swagger.io/"
  version: 1.0.0
  title: Swagger Demo
schemes:
  - http
paths:
  "/pet":
    get:
      summary: Find pet by ID
      description: Returns a single pet
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Pet"
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
definitions:
  Pet:
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
        example: doggie
      status:
        type: string
        description: pet status in the store
        enum:
          - available
          - pending
          - sold
  ApiResponse:
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
    xml:
      name: "##default"
